# Generated by Django 6.0.7 on 2026-08-20 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_top_performer',
            field=models.BooleanField(default=False),
        ),
    ]
