# Generated by Django 6.0.7 on 2026-09-03 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0003_student_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='is_top_performer',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
